### ISSUE TITLE
Present New User with Create Account View

### ISSUE THREAD

**Issue by Bennyoak** [Crypton/statusapp#104] opened 2015-08-31 19:37 UTC
Since we don't offer user selected passwords yet, there's no reason to present new users with a login screen. Instead, if a lastUser isn't detected, present the Create Account view.

**Comment by daviddahl** [comment] 2015-08-31 19:38
:+1:

**Comment by daviddahl** [comment] 2015-09-08 19:20
i think this is a duplicate of #119

**Closed by daviddahl** 2015-09-08 19:20 UTC
Labels: design, enhancement
