### ISSUE TITLE
Feature recommendation - Trusted Notification

### ISSUE THREAD

**Issue by cHRIScDammit** [Crypton/statusapp#30] opened 2015-05-01 16:03 UTC
When I exchange cards with another person, I don't have any way to know that they have added me as contact and can therefore see my content. It would be valuable to know once I've been added without having to ask them.

**Comment by daviddahl** [comment] 2015-05-01 18:13
Yes, this is in my head. Once we have the Crypton "timeline" table, we can discover that someone has added you as a contact and can note this in a "pending contacts" Item, which will be discoverable from the Conatcts screen

**Comment by daviddahl** [comment] 2015-07-02 20:34
This is sort of implemented lazily now. You will see new contacts pop up in your contacts screen that are "not trusted". More work to do yet....

**Comment by daviddahl** [comment] 2015-07-09 23:31
this seems like a duplicate of #38

**Closed by daviddahl** 2015-07-09 23:31 UTC
Labels: enhancement
