### ISSUE TITLE
Need automated testing setup with 2 or more Genymotion devices

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#2] opened 2015-01-05 05:59 UTC
@devgeeks how hard is this? I can buy licenses if need be. I figure I have a spare machine that can just crank out testing whenever I commit a change.

**Comment by helveticade** [comment] 2015-08-28 17:22
How different is this to #16 ?

**Comment by helveticade** [comment] 2015-08-28 17:22
Duplicate of #16

**Closed** 2015-08-28 17:22 UTC
Labels: help wanted
